apiVersion: v1
kind: Secret
metadata:
  name: portieris-certs
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  serverCert.pem: {{ .Files.Get "certs/serverCert.pem" | b64enc }}
  serverKey.pem: {{ .Files.Get "certs/serverKey.pem" | b64enc }}
  ca.pem: {{ .Files.Get "certs/ca.pem" | b64enc }}
